services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - "backend"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - "backend"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # init.sql will be executed on the first run
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  backend:

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
